package com.riseup.clone.data.security

import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The raw AES/GCM encrypt/decrypt step, factored out of [KeystoreCredentialStore]
 * so the crypto is a small, key-agnostic seam.
 *
 * Why this shape matters: `AES/GCM/NoPadding` via the standard JCE runs the exact
 * same code path whether [SecretKey] came from the `AndroidKeyStore` provider
 * (production) or from a plain `KeyGenerator.getInstance("AES")` on the JVM. That
 * lets [AesGcmCipherTest] prove the encrypt/decrypt round-trip (and tamper
 * detection) with a locally generated key on this build machine, even though the
 * AndroidKeyStore provider itself does not exist off-device.
 *
 * GCM is used (not CBC) because it is authenticated: any change to the ciphertext,
 * IV, or a wrong key is caught as an [javax.crypto.AEADBadTagException] on decrypt
 * rather than silently returning garbage. A fresh random IV is generated by the
 * cipher for every [seal]; reusing an IV under the same key would be catastrophic
 * for GCM, so we never supply one — we let the provider choose and store it
 * alongside the ciphertext.
 */
internal class AesGcmCipher {

    /** Ciphertext plus the IV needed to decrypt it. Neither is secret on its own. */
    data class Sealed(val iv: ByteArray, val ciphertext: ByteArray) {
        // Value semantics on byte arrays so tests can assert on equality.
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is Sealed) return false
            return iv.contentEquals(other.iv) && ciphertext.contentEquals(other.ciphertext)
        }

        override fun hashCode(): Int = 31 * iv.contentHashCode() + ciphertext.contentHashCode()
    }

    /** Encrypt [plaintext] under [key], returning the ciphertext and its generated IV. */
    fun seal(key: SecretKey, plaintext: ByteArray): Sealed {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        // The IV is chosen by the provider (required for AndroidKeyStore keys) and
        // read back out — it must be persisted with the ciphertext to decrypt later.
        return Sealed(iv = cipher.iv, ciphertext = cipher.doFinal(plaintext))
    }

    /**
     * Decrypt a [Sealed] blob under [key]. Throws (via JCE) if the key is wrong or
     * the ciphertext/IV was tampered with — callers treat that as "no valid
     * credential" rather than trusting a partial result.
     */
    fun open(key: SecretKey, sealed: Sealed): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, sealed.iv))
        return cipher.doFinal(sealed.ciphertext)
    }

    private companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
    }
}
